version: "3.7"

services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data-dev:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=guest
      - HTTP_PASSWORD=guest
    ports:
      - 8081:8081
    depends_on:
      - redis